name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies for API
        working-directory: api
        run: npm install

      - name: Install Dependencies for Web App
        working-directory: webapp
        run: npm install
        